"""Keyterms и replace для Deepgram STT."""

KEYTERMS: list[str] = [
    "QA",
    "AQA",
    "QC",
    "Manual QA",
    "Automation QA",
    "Quality Assurance",
    "автотесты",
    "автоматизация тестирования",
    "регрессионное тестирование",
    "smoke testing",
    "sanity testing",
    "integration testing",
    "end-to-end",
    "e2e",
    "API testing",
    "status code",
    "schema validation",
    "UI testing",
    "backend testing",
    "тест-дизайн",
    "тест-дизайна",
    "классы эквивалентности",
    "граничные значения",
    "boundary value analysis",
    "pairwise testing",
    "test case",
    "checklist",
    "Jira",
    "Confluence",
    "Python",
    "Pytest",
    "pytest",
    "pytest fixture",
    "pytest fixtures",
    "fixtures",
    "conftest",
    "parametrize",
    "monkeypatch",
    "Selenium",
    "Playwright",
    "Page Object",
    "Page Object Model",
    "POM",
    "REST API",
    "HTTP",
    "HTTPS",
    "Swagger",
    "OpenAPI",
    "Postman",
    "HTTPX",
    "Requests",
    "Pydantic",
    "FastAPI",
    "PostgreSQL",
    "SQL",
    "Docker",
    "GitLab CI",
    "CI/CD",
    "CICD",
    "flaky tests",
    "флейки тесты",
    "флейковые тесты",
    "Jenkins",
    "Allure",
    "Kubernetes",
    "Kafka",
    "SOLID",
    "ООП",
    "OOP",
    "Linux",
    "grep",
    "find",
    "bash",
    "ISTQB",
    "Shift-left",
    "BDD",
    "TDD",
    "WebSocket",
    "gRPC",
    "OAuth",
    "JWT",
]

# Nova-2 fallback (keywords=слово:вес)
RU_KEYWORDS: list[str] = [
    "pytest:3",
    "Pytest:3",
    "тест-дизайн:3",
    "Linux:3",
    "grep:3",
    "ООП:3",
    "OOP:3",
    "REST API:3",
    "Playwright:2",
    "Selenium:2",
    "CI/CD:2",
    "CICD:2",
    "flaky tests:2",
    "status code:2",
    "schema validation:2",
    "Page Object Model:2",
    "флейковые тесты:2",
    "флейки тесты:2",
    "AQA:2",
    "ISTQB:2",
]

# Deepgram streaming replace (известные систематические ошибки STT)
STT_REPLACE: list[tuple[str, str]] = [
    ("линзе", "Linux"),
    ("линза", "Linux"),
    ("по тесту", "pytest"),
    ("по тестам", "pytest"),
    ("алопа", "OOP"),
    ("аэроэстопе", "REST API"),
    ("рест апи", "REST API"),
]


def all_keyterms() -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for term in KEYTERMS:
        key = term.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(term)
    return out[:150]


# Flux: короткий список EN IT-терминов (Configure после connect, не в URL)
FLUX_KEYTERMS: list[str] = [
    "pytest",
    "Pytest",
    "pytest fixture",
    "pytest fixtures",
    "fixtures",
    "parametrize",
    "conftest",
    "REST API",
    "Linux",
    "grep",
    "find",
    "bash",
    "CI/CD",
    "CICD",
    "flaky tests",
    "status code",
    "schema validation",
    "Page Object Model",
    "POM",
    "Jenkins",
    "GitLab CI",
    "Docker",
    "Kubernetes",
    "Playwright",
    "Selenium",
    "Postman",
    "Swagger",
    "OpenAPI",
    "PostgreSQL",
    "Kafka",
    "OOP",
    "SOLID",
    "AQA",
    "QA",
    "ISTQB",
    "HTTP",
    "API",
    "API testing",
    "JSON",
    "monkeypatch",
    "BDD",
    "TDD",
    "WebSocket",
    "gRPC",
]
