/** Canonical QA/AQA interview questions for intent matching. */
export const QA_QUESTION_BANK: string[] = [
  'Что такое CI/CD?',
  'Что такое Jenkins?',
  'Как ты настраивал pipeline?',
  'Что такое GitLab CI?',
  'Как ты использовал Docker?',
  'Что такое REST API?',
  'Как ты проверял HTTP методы?',
  'Что такое pytest fixtures?',
  'Что такое Page Object Model?',
  'Как ты проверял Kafka?',
  'Что такое Linux?',
  'Какие бывают Linux команды?',
  'Что такое OOP?',
  'Расскажи про полиморфизм.',
  'Что такое полиморфизм?',
  'Что такое Allure Report?',
  'Как ты запускал Playwright?',
  'Чем smoke testing отличается от regression testing?',
];
